name: Regina Chen
title: Regina Chen | Software Engineer
author: Regina Chen
description: Software engineer at Karat. Previously computer science + Japanese
  at UT Austin. Passionate for clean code and aesthetic design.
url: http://reginaychen.me

resume_dir: assets/resumes/Regina_Chen.pdf

css_path: css/styles.css
